document.documentElement.style.visibility='hidden';
const gate=document.createElement('script'); gate.src='access-gate.js'; document.head.append(gate);
const mode=document.body.dataset.mode;
const isPurchase=mode==='purchase';
const DATA_URL='https://raw.githubusercontent.com/czariaiai-cell/my-news-feed/main/data/mieszkania.json';
const TODAY='2026-09-06';
const fmt=new Intl.NumberFormat('pl-PL');
const val=v=>(v===undefined||v===null||v===''||v==='unknown')?'—':String(v);
const money=v=>val(v)==='—'?'—':`${fmt.format(Number(v))} zł`;
const esc=s=>{const d=document.createElement('div');d.textContent=val(s);return d.innerHTML};
const score=r=>Number.isFinite(Number(r.ranking_score))?Number(r.ranking_score):null;
const price=r=>Number(isPurchase?r.asking_price_pln:r.owner_rent_pln);
const m2=r=>Number(isPurchase?r.price_per_m2_pln:r.rent_per_m2_pln);
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2}
function card(r){const p=isPurchase?money(r.asking_price_pln):money(r.owner_rent_pln);const per=isPurchase?val(r.price_per_m2_pln)+' zł/m²':val(r.rent_per_m2_pln)+' zł/m² owner-rent';const facts=isPurchase?`<div><b>Metraż</b><br>${esc(r.area_m2)} m²</div><div><b>Pokoje</b><br>${esc(r.rooms)}</div><div><b>Opłata</b><br>${money(r.admin_fee_pln)}</div><div><b>Stan</b><br>${esc(r.property_condition)}</div><div><b>Ogrzewanie</b><br>${esc(r.heating_type)}</div><div><b>Wynik</b><br>${score(r)??'—'}/100</div>`:`<div><b>Metraż</b><br>${esc(r.area_m2)} m²</div><div><b>Pokoje</b><br>${esc(r.rooms)}</div><div><b>Owner rent</b><br>${money(r.owner_rent_pln)}</div><div><b>Całość/mies.</b><br>${money(r.monthly_total_cost_pln)}</div><div><b>Opłata</b><br>${money(r.admin_fee_pln)}</div><div><b>Stan</b><br>${esc(r.property_condition)}</div>`;return `<article class="card ${r.status!=='active'?'uncertain':''}"><div class="meta"><span class="pill">${r.status==='active'?'aktywne':'niepewne'}</span>${String(r.first_seen)===TODAY?'<span class="pill">NOWE DZIŚ</span>':''}<span>pierwszy zapis: ${esc(r.first_seen)}</span></div><h3>${esc(r.title||'Oferta bez tytułu')}</h3><div class="address">${esc(r.address||r.address_or_area||r.district_area||r.area_focus)}</div><div class="price">${p}</div><div class="address">${per}</div><div class="facts">${facts}</div><div class="note">${esc((r.investment_fit||r.notes||'').slice(0,300))}</div><a class="listing" href="${esc(r.url)}" target="_blank" rel="noopener">Otwórz ogłoszenie ↗</a></article>`}
function render(data){if(!data)return;const all=isPurchase?data.purchase:data.rental;const status=document.getElementById('status').value;const q=document.getElementById('search').value.toLowerCase();const sort=document.getElementById('sort').value;let rows=all.filter(r=>status==='all'||status==='new_today'?true:r.status===status).filter(r=>status!=='new_today'||String(r.first_seen)===TODAY).filter(r=>Object.values(r).join(' ').toLowerCase().includes(q));rows.sort((a,b)=>sort==='new'?String(b.first_seen).localeCompare(String(a.first_seen)):sort==='price'?price(a)-price(b):isPurchase?(score(b)??-1)-(score(a)??-1):m2(a)-m2(b));document.getElementById('count').textContent=`${rows.length} ofert`;document.getElementById('cards').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">Brak ofert spełniających filtr.</div>';const active=all.filter(r=>r.status==='active');const vals=active.map(m2).filter(Number.isFinite);const newToday=all.filter(r=>String(r.first_seen)===TODAY);document.getElementById('snapshot-date').textContent=`Snapshot: ${val(data.generated_at)} · ${isPurchase?'kupno':'najem'} · ${active.length} aktywnych · ${newToday.length} nowych dziś`;document.getElementById('metric-grid').innerHTML=`<div class="metric"><span>Aktywne oferty</span><b>${active.length}</b></div><div class="metric"><span>Wszystkie rekordy</span><b>${all.length}</b></div><div class="metric"><span>Nowe dziś</span><b>${newToday.length}</b></div><div class="metric"><span>${isPurchase?'Mediana ceny/m²':'Mediana owner-rent/m²'}</span><b>${median(vals)?.toFixed(2)??'—'} zł</b></div>`;document.getElementById('insights').innerHTML=`<div class="insight"><b>Dane produkcyjne</b><br>Strona pobiera aktualny <b>data/mieszkania.json</b> bezpośrednio z GitHub, niezależnie od lokalnej kopii Pages.</div><div class="insight"><b>Nowe na dziś</b><br>Liczone wyłącznie po <b>first_seen = ${TODAY}</b>. Data snapshotu sama w sobie nie tworzy nowych ofert.</div>`}
async function load(){try{const r=await fetch(`${DATA_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d.purchase)||!Array.isArray(d.rental))throw new Error('Nieprawidłowa struktura JSON');window.mieszkaniaData=d;render(d);document.getElementById('status-message').textContent='Dane załadowane bezpośrednio z GitHub ✓';document.documentElement.style.visibility='visible'}catch(e){document.documentElement.style.visibility='visible';document.getElementById('status-message').textContent=`BŁĄD DANYCH: ${e.message}`}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('search').addEventListener('input',()=>render(window.mieszkaniaData));document.getElementById('status').addEventListener('change',()=>render(window.mieszkaniaData));document.getElementById('sort').addEventListener('change',()=>render(window.mieszkaniaData));load()});
