document.documentElement.style.visibility='hidden';
const gate=document.createElement('script'); gate.src='access-gate.js'; document.head.append(gate);
const mode=document.body.dataset.mode;
const isPurchase=mode==='purchase';
const DATA_URL='https://raw.githubusercontent.com/czariaiai-cell/my-news-feed/main/data/mieszkania.json';
const TODAY='2026-09-06';
const fmt=new Intl.NumberFormat('pl-PL');
const val=v=>(v===undefined||v===null||v===''||v==='unknown')?'—':String(v);
const money=v=>val(v)==='—'?'—':`${fmt.format(Number(v))} zł`;
const esc=s=>{const d=document.createElement('div');d.textContent=val(s);return d.innerHTML};
const score=r=>Number.isFinite(Number(r.ranking_score))?Number(r.ranking_score):null;
const price=r=>Number(isPurchase?r.asking_price_pln:r.owner_rent_pln);
const m2=r=>Number(isPurchase?r.price_per_m2_pln:r.rent_per_m2_pln);
const linkStatus=r=>String(r.link_status||r.verification_status||'').toLowerCase();
const isDirect=r=>linkStatus(r).includes('direct verified')||linkStatus(r).includes('verified_on_listing_page');
const isSearch=r=>linkStatus(r).includes('search')||linkStatus(r).includes('unverified')||linkStatus(r).includes('uncertain');
const portalOf=r=>{const u=String(r.url||'').toLowerCase(); if(u.includes('olx.pl'))return 'OLX'; if(u.includes('otodom.pl'))return 'Otodom'; if(u.includes('morizon.pl'))return 'Morizon'; if(u.includes('gratka.pl'))return 'Gratka'; if(u.includes('adresowo.pl'))return 'Adresowo'; if(u.includes('nieruchomosci-online.pl'))return 'Nieruchomosci-online'; if(u.includes('domiporta.pl'))return 'Domiporta'; if(u.includes('gethome.pl'))return 'GetHome'; return 'portal';};
const searchUrl=r=>{if(r.search_url)return r.search_url; const q=[r.title,r.address,r.area_m2?`${r.area_m2} m²`:'',r.asking_price_pln?`${r.asking_price_pln} zł`:''].filter(Boolean).join(' '); const u=String(r.url||'').toLowerCase(); if(u.includes('olx.pl')) return 'https://www.olx.pl/nieruchomosci/mieszkania/sprzedaz/q-'+encodeURIComponent(q.toLowerCase().replace(/\s+/g,'-'))+'/'; return ''};
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2}
function linkBlock(r){const alternatives=Array.isArray(r.alternative_urls)?r.alternative_urls.filter(Boolean):[]; if(isDirect(r)&&r.url)return `<a class="listing" href="${esc(r.url)}" target="_blank" rel="noopener">Otwórz potwierdzone ogłoszenie ↗</a>`; let html=''; alternatives.forEach((u,i)=>{html+=`<a class="listing" href="${esc(u)}" target="_blank" rel="noopener">Alternatywny portal ${i+1} ↗</a>`}); const s=searchUrl(r); if(s) html+=`<a class="listing" href="${esc(s)}" target="_blank" rel="noopener">${portalOf(r)} — szukaj dokładnego ogłoszenia ↗</a>`; if(!html) html=`<div class="listing disabled" title="Brak potwierdzonego działającego linku">Brak potwierdzonego linku — oferta wymaga dalszej weryfikacji</div>`; return html}
function card(r){const p=isPurchase?money(r.asking_price_pln):money(r.owner_rent_pln);const per=isPurchase?val(r.price_per_m2_pln)+' zł/m²':val(r.rent_per_m2_pln)+' zł/m² owner-rent';const facts=isPurchase?`<div><b>Metraż</b><br>${esc(r.area_m2)} m²</div><div><b>Pokoje</b><br>${esc(r.rooms)}</div><div><b>Opłata</b><br>${money(r.admin_fee_pln)}</div><div><b>Stan</b><br>${esc(r.property_condition)}</div><div><b>Ogrzewanie</b><br>${esc(r.heating_type)}</div><div><b>Wynik</b><br>${score(r)??'—'}/100</div>`:`<div><b>Metraż</b><br>${esc(r.area_m2)} m²</div><div><b>Pokoje</b><br>${esc(r.rooms)}</div><div><b>Owner rent</b><br>${money(r.owner_rent_pln)}</div><div><b>Całość/mies.</b><br>${money(r.monthly_total_cost_pln)}</div><div><b>Opłata</b><br>${money(r.admin_fee_pln)}</div><div><b>Stan</b><br>${esc(r.property_condition)}</div>`;const alternatives=Array.isArray(r.alternative_urls)?r.alternative_urls.length:0;const state=isDirect(r)?'🟢 direct verified':alternatives?'🟡 alternatywny link potwierdzony':isSearch(r)?'🔵 wyszukiwanie portalu':'🔴 niezweryfikowane';return `<article class="card ${r.status!=='active'?'uncertain':''}"><div class="meta"><span class="pill">${r.status==='active'?'aktywne':'niepewne'}</span><span class="pill">${state}</span>${String(r.first_seen)===TODAY?'<span class="pill">NOWE DZIŚ</span>':''}<span>pierwszy zapis: ${esc(r.first_seen)}</span></div><h3>${esc(r.title||'Oferta bez tytułu')}</h3><div class="address">${esc(r.address||r.address_or_area||r.district_area||r.area_focus)}</div><div class="price">${p}</div><div class="address">${per}</div><div class="facts">${facts}</div><div class="note">${esc((r.investment_fit||r.notes||'').slice(0,300))}</div>${linkBlock(r)}</article>`}
function render(data){if(!data)return;const all=isPurchase?data.purchase:data.rental;const status=document.getElementById('status').value;const q=document.getElementById('search').value.toLowerCase();const sort=document.getElementById('sort').value;let rows=all.filter(r=>status==='all'||status==='new_today'?true:r.status===status).filter(r=>status!=='new_today'||String(r.first_seen)===TODAY).filter(r=>Object.values(r).join(' ').toLowerCase().includes(q));rows.sort((a,b)=>sort==='new'?String(b.first_seen).localeCompare(String(a.first_seen)):sort==='price'?price(a)-price(b):isPurchase?(score(b)??-1)-(score(a)??-1):m2(a)-m2(b));document.getElementById('count').textContent=`${rows.length} ofert`;document.getElementById('cards').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">Brak ofert spełniających filtr.</div>';const active=all.filter(r=>r.status==='active');const vals=active.map(m2).filter(Number.isFinite);const newToday=all.filter(r=>String(r.first_seen)===TODAY);const direct=active.filter(isDirect).length;const alt=active.filter(r=>Array.isArray(r.alternative_urls)&&r.alternative_urls.length).length;document.getElementById('snapshot-date').textContent=`Snapshot: ${val(data.generated_at)} · ${isPurchase?'kupno':'najem'} · ${active.length} aktywnych · ${newToday.length} nowych dziś`;document.getElementById('metric-grid').innerHTML=`<div class="metric"><span>Aktywne oferty</span><b>${active.length}</b></div><div class="metric"><span>Wszystkie rekordy</span><b>${all.length}</b></div><div class="metric"><span>Nowe dziś</span><b>${newToday.length}</b></div><div class="metric"><span>Link direct verified</span><b>${direct}</b></div><div class="metric"><span>Alternatywny link</span><b>${alt}</b></div><div class="metric"><span>${isPurchase?'Mediana ceny/m²':'Mediana owner-rent/m²'}</span><b>${median(vals)?.toFixed(2)??'—'} zł</b></div>`;document.getElementById('insights').innerHTML=`<div class="insight"><b>Dane produkcyjne</b><br>Strona pobiera aktualny <b>data/mieszkania.json</b> bezpośrednio z GitHub.</div><div class="insight"><b>Logika linków</b><br>Najpierw direct verified, następnie potwierdzony alternatywny portal, a na końcu dokładne wyszukiwanie po tytule/opisie. Niepotwierdzony direct nie jest klikalny jako działające ogłoszenie.</div>`}
async function load(){try{const r=await fetch(`${DATA_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d.purchase)||!Array.isArray(d.rental))throw new Error('Nieprawidłowa struktura JSON');window.mieszkaniaData=d;render(d);document.getElementById('status-message').textContent='Dane załadowane bezpośrednio z GitHub ✓';document.documentElement.style.visibility='visible'}catch(e){document.documentElement.style.visibility='visible';document.getElementById('status-message').textContent=`BŁĄD DANYCH: ${e.message}`}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('search').addEventListener('input',()=>render(window.mieszkaniaData));document.getElementById('status').addEventListener('change',()=>render(window.mieszkaniaData));document.getElementById('sort').addEventListener('change',()=>render(window.mieszkaniaData));load()});
